"""YAML round-trip for the committed source of truth in ``data/``.

The YAML is the artifact humans review and diff. The extractor writes it;
every emitter reads it. Nothing downstream re-scrapes.
"""
from __future__ import annotations

import datetime as _dt
from pathlib import Path

import yaml

from .model import AcademicYear, Event, Term, link


def _event_to_yaml(e: Event) -> dict:
    d: dict = {'date': e.date, 'label': e.label, 'kinds': e.kinds}
    if e.no_classes:
        d['no_classes'] = True
    if e.observes_schedule_of:
        d['observes_schedule_of'] = e.observes_schedule_of
    if e.offices_closed is not None:
        d['offices_closed'] = e.offices_closed
    if e.span_id:
        d['span_id'] = e.span_id
    if e.source_text:
        d['source_text'] = e.source_text
    if e.stated_day:
        d['stated_day'] = e.stated_day
    if e.session:
        d['session'] = e.session
    return d


def to_yaml(ay: AcademicYear) -> str:
    doc = {
        'academic_year': ay.academic_year,
        'unofficial': True,
        'source_url': ay.source_url,
        'retrieved': ay.retrieved,
        'terms': [
            {
                'id': t.id,
                'term': t.term,
                'classes_begin': t.classes_begin,
                'classes_end': t.classes_end,
                'events': [_event_to_yaml(e) for e in t.events],
            }
            for t in ay.terms
        ],
    }
    header = (
        '# UNOFFICIAL, derived from the RWU public academic calendar page.\n'
        '# Generated by `rwu-calendar extract` -- edit and commit deliberately.\n'
        f'# Source: {ay.source_url}\n'
    )
    return header + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, width=100)


def _as_date(v) -> _dt.date:
    return v if isinstance(v, _dt.date) else _dt.date.fromisoformat(str(v))


def from_yaml(text: str) -> AcademicYear:
    doc = yaml.safe_load(text)
    ay = AcademicYear(doc['academic_year'], doc['source_url'], str(doc['retrieved']))
    for t in doc.get('terms') or []:
        term = Term(id=t['id'], term=t['term'], academic_year=ay.academic_year)
        for e in t.get('events') or []:
            term.events.append(Event(
                date=_as_date(e['date']), label=e['label'], kinds=list(e.get('kinds') or []),
                no_classes=bool(e.get('no_classes', False)),
                offices_closed=e.get('offices_closed'),
                observes_schedule_of=e.get('observes_schedule_of'),
                span_id=e.get('span_id'), source_text=e.get('source_text', ''),
                stated_day=e.get('stated_day', ''), session=e.get('session'),
            ))
        ay.terms.append(term)
    return link(ay)


def load_dir(path: str | Path) -> list[AcademicYear]:
    return [from_yaml(p.read_text(encoding='utf-8'))
            for p in sorted(Path(path).glob('*.yaml'))]


def write_dir(years: list[AcademicYear], path: str | Path) -> list[Path]:
    out = Path(path)
    out.mkdir(parents=True, exist_ok=True)
    written = []
    for ay in years:
        f = out / f'{ay.academic_year}.yaml'
        f.write_text(to_yaml(ay), encoding='utf-8')
        written.append(f)
    return written
